### ISSUE TITLE
2 Steps switch instead of direct lock/unlock (and by the way it works well with Yale Linus + Bridge)

### ISSUE THREAD

**Issue by tmenguy** [blaineam/homebridge-august-smart-locks#49]
Hi, 

Thanks a lot for this plugin, I use it successfully with my Yale Linus Lock with its bridge (that is in fact an august one).

Only minor issues I have : 
-the button in homekit needs 2 steps : first click on the lock in the app, it opens a virtual switch and from here you can open (or close) the lock. The direct Yale integration is better in that regard : clicking on the home app lock icon will indeed open or close the door without the extra step.
-when opening/closing the state of the lock is at "unresponsive", need to close/open the homeapp and everything is fine

BR

**Comment by mjwillson23** [comment]
I noticed this too, I believe this is because it imports the contact sensor as well as the lock, so there are actually 2 accessories there.  I do not even have the separate door sensor setup in the August app and Homebridge still imports it into Homekit for some reason.  I think having a way to delete/exclude the door sensors would solve this problem.

**Comment by 3ne** [comment]
I'm not sure why but I am able to use the lock button in one step. I have a August Smart Lock (no native HomeKit support) with the doorsense. It shows both the lock and sensor, I have the sensor displayed as a door and the lock set to display in favourites.
